name: concat_refdata
on:
  workflow_run:
    workflows: [refdata_quality_check, check_all]
    types: [completed]
jobs:
  concatenate_refdata:
    runs-on: ubuntu-latest
    name: Concatenate mappings and lookups
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Load triggering branch name (if any) as an artifact
      - name: Load branch name
        if: ${{ github.event.workflow_run.name == 'check_all' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: triggering_branch_name
      
      - name: Assign branch name to variable
        id: output_branch_name
        run: |
          input_file="current_name.txt"
          while read line
          do
            file_text=$line
          done < "$input_file"
          echo ::set-output name=new_value::$file_text

      - name: Checkout repo content
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.output_branch_name.outputs.new_value }}
          fetch-depth: 0

      # Run concatenation on MAP files and push output file into repo
      - name: Run concatenation on mapping file(s)
        working-directory: ./src
        run: |
          python concat_rd.py -o ../tests_deploy/mapping.csv ../tests/**_MAP.csv
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ../tests_deploy/mapping.csv
          git commit -m "Github Actions auto-generated concatenation"

      # Run concatenation on LKP files and push output file into repo
      - name: Run concatenation on lookup file(s)
        working-directory: ./src
        run: |
          python concat_rd.py -o ../tests_deploy/lookup.csv ../tests/**_LKP.csv
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ../tests_deploy/lookup.csv
          git commit -m "Github Actions auto-generated concatenation"
      
      # Push the committed changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true